[package]
name = "logtool"
version = "0.1.0"
edition = "2021"

[dependencies]
encoding_rs = "0.8.34"
encoding_rs_io = "0.1.7"
iced = { git = "https://github.com/iced-rs/iced", features = ["smol", "advanced"] }
notify = "6.1.1"
smol = "2.0.0"

